import { Redis } from "@upstash/redis";
const redis = new Redis({ url: process.env.UPSTASH_REDIS_REST_URL, token: process.env.UPSTASH_REDIS_REST_TOKEN });
function profileKey(email) { return "il:mat:profile:" + email.toLowerCase().replace(/[^a-z0-9]/g, "_"); }

const VIRTUAL_WOMEN = [
  {
    email: "virtual.aisha@theinternationallover.com",
    gender: "woman",
    displayName: "Aisha",
    age: 27,
    city: "Atlanta, Georgia",
    country: "North America",
    region: "us",
    religion: "Muslim",
    bio: `Born Muslim. Her father was one of the first men in his neighborhood to take shahada in the 1980s. She has been waiting for a man who understands what that means.`,
    photoUrl: "/women/aisha.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000000000,
  },
  {
    email: "virtual.deborah@theinternationallover.com",
    gender: "woman",
    displayName: "Deborah",
    age: 29,
    city: "Washington D.C.",
    country: "North America",
    region: "us",
    religion: "Hebrew Israelite",
    bio: `She has been in the Hebrew Israelite community her whole life. The law is not a burden — it is the framework she was raised inside and has chosen to remain inside as an adult.`,
    photoUrl: "/women/deborah.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000001000,
  },
  {
    email: "virtual.kezia@theinternationallover.com",
    gender: "woman",
    displayName: "Kezia",
    age: 26,
    city: "Houston, Texas",
    country: "North America",
    region: "us",
    religion: "Christian",
    bio: `Not a cultural Christian. She reads. She fasts. She tithes because she decided to. She is waiting for a man who has a relationship with God that is his own, not borrowed.`,
    photoUrl: "/women/kezia.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000002000,
  },
  {
    email: "virtual.marisol@theinternationallover.com",
    gender: "woman",
    displayName: "Marisol",
    age: 28,
    city: "Chicago, Illinois",
    country: "North America",
    region: "us",
    religion: "Catholic",
    bio: `Mexican-American. Third generation. Her grandmother came from Jalisco. Her faith is woven into everything her family does.`,
    photoUrl: "/women/marisol.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000003000,
  },
  {
    email: "virtual.samira@theinternationallover.com",
    gender: "woman",
    displayName: "Samira",
    age: 25,
    city: "Miami, Florida",
    country: "North America",
    region: "us",
    religion: "Islam (revert)",
    bio: `Puerto Rican. Took shahada four years ago. Her family is Catholic. Her faith is real — tested, chosen, and maintained against the current of her own culture.`,
    photoUrl: "/women/samira.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000004000,
  },
  {
    email: "virtual.nour.us@theinternationallover.com",
    gender: "woman",
    displayName: "Nour",
    age: 27,
    city: "Dearborn, Michigan",
    country: "North America",
    region: "us",
    religion: "Islam",
    bio: `Born in Dearborn. Her parents came from Lebanon. She is American in her fluency and Arab in her framework. The family meeting in Dearborn is not different from the family meeting in Beirut.`,
    photoUrl: "/women/nour-us.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000005000,
  },
  {
    email: "virtual.rachel@theinternationallover.com",
    gender: "woman",
    displayName: "Rachel",
    age: 26,
    city: "Portland, Oregon",
    country: "North America",
    region: "us",
    religion: "Islam (revert)",
    bio: `Took shahada eighteen months ago. Her practice is sincere. Her knowledge is growing. Her foundation is thin. She is using the idea of a husband to fill the space where a community should be.`,
    photoUrl: "/women/rachel.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000006000,
  },
  {
    email: "virtual.nadia@theinternationallover.com",
    gender: "woman",
    displayName: "Nadia",
    age: 24,
    city: "Fez, Morocco",
    country: "North Africa",
    region: "na",
    religion: "Muslim (practicing)",
    bio: `I am a teacher. I love books and the Arabic language. I come from a family that holds education and faith as its highest values. I am not looking for adventure. I am looking for a husband who is serious about building a home. My father will speak for me when the time is right.`,
    photoUrl: "/women/nadia.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000007000,
  },
  {
    email: "virtual.yasmine@theinternationallover.com",
    gender: "woman",
    displayName: "Yasmine",
    age: 22,
    city: "Casablanca, Morocco",
    country: "North Africa",
    region: "na",
    religion: "Muslim (moderate)",
    bio: `I am a young woman who loves life, travel, and learning new things. American men seem to understand women better than men here. I want a partner who will treat me with respect. I believe love has no borders.`,
    photoUrl: "/women/yasmine.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000008000,
  },
  {
    email: "virtual.fatima@theinternationallover.com",
    gender: "woman",
    displayName: "Fatima-Zahra",
    age: 27,
    city: "Meknes, Morocco",
    country: "North Africa",
    region: "na",
    religion: "Muslim (deeply practicing)",
    bio: `I seek a husband who fears Allah and leads his home with knowledge and wisdom. My father will conduct all initial communications on my behalf. If you are serious, write to him directly.`,
    photoUrl: "/women/fatima.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000009000,
  },
  {
    email: "virtual.sara@theinternationallover.com",
    gender: "woman",
    displayName: "Sara",
    age: 26,
    city: "Amman, Jordan",
    country: "Middle East",
    region: "me",
    religion: "Muslim (practicing)",
    bio: `I am a nurse and I believe in service. I am looking for a man who understands that a good wife is built from character, not from beauty. I have my parents blessing to use this platform. I am ready for marriage. I am not ready for games.`,
    photoUrl: "/women/sara.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000010000,
  },
  {
    email: "virtual.hessa@theinternationallover.com",
    gender: "woman",
    displayName: "Hessa",
    age: 23,
    city: "Beirut, Lebanon",
    country: "Middle East",
    region: "me",
    religion: "Muslim (cultural)",
    bio: `I am curious about everything. I believe the world is larger than where you were born. I am looking for a man who is going somewhere and who wants to take me with him.`,
    photoUrl: "/women/hessa.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000011000,
  },
  {
    email: "virtual.maryam@theinternationallover.com",
    gender: "woman",
    displayName: "Maryam",
    age: 29,
    city: "Irbid, Jordan",
    country: "Middle East",
    region: "me",
    religion: "Muslim (deeply practicing)",
    bio: `I have spent my life studying words. I understand their weight. I will not spend them carelessly here. I am looking for a man of substance. My brother manages this account on my behalf.`,
    photoUrl: "/women/maryam.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000012000,
  },
  {
    email: "virtual.amira@theinternationallover.com",
    gender: "woman",
    displayName: "Amira",
    age: 25,
    city: "Yogyakarta, Indonesia",
    country: "Asia",
    region: "as",
    religion: "Muslim (traditionalist)",
    bio: `My family is my world. My faith is my foundation. I am not looking for a man to take me somewhere. I am looking for a man to build something with me — here or wherever Allah wills. My father speaks for me.`,
    photoUrl: "/women/amira.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000013000,
  },
  {
    email: "virtual.jasmine@theinternationallover.com",
    gender: "woman",
    displayName: "Jasmine",
    age: 24,
    city: "Cebu, Philippines",
    country: "Asia",
    region: "as",
    religion: "Catholic",
    bio: `Family is everything to me. I take care of my parents and my two younger brothers. I want a husband who understands that when you marry me, you marry my whole family. Not in a burden way — in a love way.`,
    photoUrl: "/women/jasmine.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000014000,
  },
  {
    email: "virtual.nurul@theinternationallover.com",
    gender: "woman",
    displayName: "Nurul",
    age: 28,
    city: "Dhaka, Bangladesh",
    country: "Asia",
    region: "as",
    religion: "Muslim (practicing privately)",
    bio: `I believe marriage is a partnership. I am not looking to be managed. I am looking for a man who is secure enough to be beside me rather than above me. I am traditional in my values and contemporary in my methods.`,
    photoUrl: "/women/nurul.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000015000,
  },
  {
    email: "virtual.valentina@theinternationallover.com",
    gender: "woman",
    displayName: "Valentina",
    age: 27,
    city: "Medellin, Colombia",
    country: "Latin America",
    region: "la",
    religion: "Catholic (practicing)",
    bio: `I believe a home needs a foundation. I am not looking for a vacation. I am looking for a husband. If you are serious, I will know. If you are not, I will also know.`,
    photoUrl: "/women/valentina.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000016000,
  },
  {
    email: "virtual.diana@theinternationallover.com",
    gender: "woman",
    displayName: "Diana",
    age: 22,
    city: "Santo Domingo, Dominican Republic",
    country: "Latin America",
    region: "la",
    religion: "Catholic (cultural)",
    bio: `I want a better life. I am not ashamed to say this. My country is difficult. I work hard and I want a man who works hard with me. I want children and a home.`,
    photoUrl: "/women/diana.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000017000,
  },
  {
    email: "virtual.elena@theinternationallover.com",
    gender: "woman",
    displayName: "Elena",
    age: 30,
    city: "Lima, Peru",
    country: "Latin America",
    region: "la",
    religion: "Catholic with indigenous traditions",
    bio: `I have spent years going into communities the city forgets. I have seen what a family without a father becomes. I do not want that for myself. I am looking for a serious man — not a perfect man, but a man who is committed to being better.`,
    photoUrl: "/women/elena.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000018000,
  },
  {
    email: "virtual.fatou@theinternationallover.com",
    gender: "woman",
    displayName: "Fatou",
    age: 26,
    city: "Dakar, Senegal",
    country: "Sub-Saharan Africa",
    region: "ss",
    religion: "Muslim (Sufi - Tijaniyya)",
    bio: `I come from a family of teachers and scholars. My grandfather was a marabout. My father is a teacher. I am a teacher. I am looking for a man who understands that a wife brings more than her body to a home — she brings her lineage, her faith, and her gifts.`,
    photoUrl: "/women/fatou.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000019000,
  },
  {
    email: "virtual.abena@theinternationallover.com",
    gender: "woman",
    displayName: "Abena",
    age: 24,
    city: "Accra, Ghana",
    country: "Sub-Saharan Africa",
    region: "ss",
    religion: "Christian (Pentecostal)",
    bio: `I believe God has a plan for every life. I believe that plan includes a good marriage and a family built on faith. I am not desperate — I am deliberate. My parents are involved in everything important that I do. This is not a warning. It is a promise.`,
    photoUrl: "/women/abena.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000020000,
  },
  {
    email: "virtual.tigist@theinternationallover.com",
    gender: "woman",
    displayName: "Tigist",
    age: 28,
    city: "Addis Ababa, Ethiopia",
    country: "Sub-Saharan Africa",
    region: "ss",
    religion: "Ethiopian Orthodox Christian",
    bio: `I am on this platform because my family asked me to consider men from outside Ethiopia. I am not certain this is the right path for me. But I am willing to be shown that it is. I am serious, faithful, and I will not waste your time if you do not waste mine.`,
    photoUrl: "/women/tigist.jpg",
    familyInvolvement: "Family involved",
    virtueStatus: "Practicing",
    maritalStatus: "Never married",
    hasChildren: "No",
    seeking: "Marriage",
    approved: true,
    hidden: false,
    isVirtual: true,
    isCertified: false,
    isAmbassador: false,
    isFounder: false,
    createdAt: 1700000021000,
  },
];

export default async function handler(req, res) {
  // Accept either:
  // - POST with { adminCode: "ADMINTEST" } — from the admin panel button
  // - GET with ?code=ADMINTEST — from browser address bar
  const code = req.method === "POST"
    ? (req.body?.adminCode || req.body?.adminKey)
    : (req.query.code || req.query.key);

  // Valid if: code is "ADMINTEST", OR code matches IL_ADMIN_KEY env var
  const validCode = code === "ADMINTEST" ||
    (process.env.IL_ADMIN_KEY && code === process.env.IL_ADMIN_KEY);

  if (!validCode) return res.status(403).json({ error: "Forbidden" });

  const results = [];
  for (const w of VIRTUAL_WOMEN) {
    try {
      const k = profileKey(w.email);
      await redis.set(k, JSON.stringify(w));
      results.push({ name: w.displayName, email: w.email, ok: true });
    } catch(e) {
      results.push({ name: w.displayName, error: String(e) });
    }
  }
  return res.status(200).json({ seeded: results.length, results });
}
